version: '3'
services:
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql-dump:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: "expPass2019!"
            MYSQL_DATABASE: "db_test_env"
        ports:
            - "3306:3306"
        networks:
            - sfmdev
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - sfmdev
    nodejs:
        build: ./nodejs
        volumes:
            - ./project/nodejs:/project/nodejs
        ports:
            - "4200:4200"
        command: node project/nodejs/server.js
        networks:
            - sfmdev
    nginx:
        image: nginx:latest
        ports:
            - "80:80" 
        volumes:
            - ./project:/project
            - ./site.conf:/etc/nginx/conf.d/site.conf
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./default.conf:/etc/nginx/conf.d/mysite.conf
        networks:
            - sfmdev
    php:
        build: ./php-fpm
        volumes:
            - ./project:/project
        ports:
            - "9000:9000"
        networks:
            - sfmdev
networks:
    sfmdev:
        driver: bridge